---
title: "Intro into R"
author: "vitaly.belik@fu-berlin.de"
date: "3/12/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
getwd()
# setwd('~/Lehre/WS1819/Spring_School/Data/')
# load("~/Lehre/WS1819/Spring_School/ver-master/data/ver2_data_R/daisy2.rdata")

# Creating arrays of values
y <- c(1,10)
y
u <- c(1:10)
u
v <- u^2
v
# Creating dataframe
df <- data.frame(u,v)
df
# Writing dataframe to file
write.csv(df, file = "MyData.csv")
list.files()
# Reading data from file
ndf <- read.csv("MyData.csv")
colnames(ndf)
summary(ndf)
# Deleting a column
Data <- subset( ndf, select = -X )
Data

# Adding a column
Data['w'] <-u
Data
# For-loop

for (i in c(1:10)){
  print(c("index :",i))
}
# Subsetting / filtering data
Data[Data$u == 1,]
Data[Data$u == 2,]
?subset
subset(Data, u > 1)

# Creating plots

plot(u,v)

load("~/Lehre/WS1819/Spring_School/ver-master/data/ver2_data_R/daisy2.rdata")
library(ggplot2)
ggplot(daisy2, aes(x = cc, y = milk120, colour = cow)) + 
  theme(text = element_text(size=18)) +
  geom_point(alpha = 0.3) +
  labs(x = "cc", y = "milk")
  
```
